# Generated by Django 5.0.2 on 2024-02-19 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_app", "0003_notehistory_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="shared_users",
            field=models.ManyToManyField(
                related_name="shared_notes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
